[package]
name = "binarygrabber"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
ureq = "2.6.2"

[dev-dependencies]
pretty_env_logger = "0.4.0"
sealed_test = "1.0.0"

